"""Canonical Novel API migration order and deterministic schema fingerprints."""

from __future__ import annotations

import hashlib
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

from .migration_constraints import CONSTRAINT_SIGNATURES
from .migration_defaults import DEFAULT_SIGNATURES

Family = Literal["novel"]
ColumnSignature = tuple[str, str, str, bool]
ConstraintSignature = tuple[str, str, str]
DefaultSignature = tuple[str, str, str]
IndexSignature = tuple[
    str,
    str,
    str,
    bool,
    bool,
    bool,
    bool,
    tuple[str, ...],
    str,
]
RelationSignature = tuple[str, str]
ViewSignature = tuple[str, str]


@dataclass(frozen=True)
class MigrationSpec:
    family: Family
    migration_id: str
    path: Path
    relations: frozenset[str] = frozenset()
    columns: frozenset[tuple[str, str]] = frozenset()
    absent_columns: frozenset[tuple[str, str]] = frozenset()
    column_signatures: frozenset[ColumnSignature] = frozenset()
    constraints: frozenset[ConstraintSignature] = frozenset()
    indexes: frozenset[IndexSignature] = frozenset()
    relation_signatures: frozenset[RelationSignature] = frozenset()
    views: frozenset[ViewSignature] = frozenset()
    defaults: frozenset[DefaultSignature] = frozenset()

    @property
    def checksum_sha256(self) -> str:
        return hashlib.sha256(self.path.read_bytes()).hexdigest()


_CATALOG = {"novel": (('20260601_novel_api_baseline',
  ('book', 'chapter', 'character', 'debt', 'hook', 'outline', 'world'),
  (),
  ()),
 ('20260609_product_schema',
  ('idx_book_external_ref',
   'idx_chapter_book_number_unique',
   'novel_job',
   'novel_job_event',
   'novel_resource_revision',
   'novel_resource_state'),
  (('book', 'external_ref'), ('book', 'genre'), ('character', 'true_name')),
  (('chapter', 'is_latest'), ('chapter', 'version'))),
 ('20260613_book_scale_params',
  (),
  (('book', 'estimated_length'), ('book', 'words_per_chapter')),
  ()),
 ('20260613_book_soft_delete', (), (('book', 'deleted_at'),), ()),
 ('20260720_novel_runtime_schema',
  ('uq_novel_job_active_operation', 'uq_novel_job_active_polish_chapter'),
  (('chapter', 'post_hoc_status'), ('character', 'essence')),
  ()))}
_COLUMN_SIGNATURES = {'20260601_novel_api_baseline': (('book',
                                  'created_at',
                                  'timestamp with time zone',
                                  False),
                                 ('book', 'id', 'uuid', True),
                                 ('book', 'story_plan', 'jsonb', True),
                                 ('book', 'style_profile', 'jsonb', True),
                                 ('book', 'title', 'text', True),
                                 ('book',
                                  'updated_at',
                                  'timestamp with time zone',
                                  False),
                                 ('chapter', 'body', 'text', False),
                                 ('chapter', 'book_id', 'uuid', True),
                                 ('chapter', 'chapter_number', 'integer', True),
                                 ('chapter', 'character_diff', 'jsonb', False),
                                 ('chapter', 'character_minor', 'jsonb', False),
                                 ('chapter', 'character_state', 'jsonb', False),
                                 ('chapter',
                                  'created_at',
                                  'timestamp with time zone',
                                  False),
                                 ('chapter', 'guide', 'jsonb', False),
                                 ('chapter', 'id', 'uuid', True),
                                 ('chapter', 'status', 'text', True),
                                 ('chapter', 'story_confirmed', 'jsonb', False),
                                 ('chapter', 'storyboard', 'jsonb', False),
                                 ('chapter', 'title', 'text', False),
                                 ('chapter',
                                  'updated_at',
                                  'timestamp with time zone',
                                  False),
                                 ('chapter', 'word_count', 'integer', False),
                                 ('chapter', 'world_events', 'jsonb', False),
                                 ('chapter', 'world_rulings', 'jsonb', False),
                                 ('chapter', 'world_state', 'jsonb', False),
                                 ('character', 'age', 'text', False),
                                 ('character', 'aliases', 'jsonb', True),
                                 ('character', 'arc_description', 'jsonb', False),
                                 ('character', 'beliefs', 'jsonb', False),
                                 ('character', 'book_id', 'uuid', True),
                                 ('character', 'bottom_line', 'jsonb', False),
                                 ('character', 'contradictions', 'jsonb', False),
                                 ('character',
                                  'created_at',
                                  'timestamp with time zone',
                                  False),
                                 ('character', 'deep_desire', 'text', False),
                                 ('character', 'deep_fear', 'jsonb', False),
                                 ('character', 'extras', 'jsonb', False),
                                 ('character', 'gender', 'text', False),
                                 ('character', 'id', 'uuid', True),
                                 ('character', 'name', 'text', True),
                                 ('character', 'role', 'text', True),
                                 ('character', 'secrets', 'jsonb', False),
                                 ('character', 'surface_goal', 'text', False),
                                 ('character', 'traumas', 'jsonb', False),
                                 ('character',
                                  'updated_at',
                                  'timestamp with time zone',
                                  False),
                                 ('character', 'voice', 'jsonb', True),
                                 ('character', 'world_position', 'jsonb', False),
                                 ('debt', 'book_id', 'uuid', True),
                                 ('debt', 'chapter_created', 'integer', False),
                                 ('debt', 'chapter_resolved', 'integer', False),
                                 ('debt', 'content', 'jsonb', False),
                                 ('debt',
                                  'created_at',
                                  'timestamp with time zone',
                                  False),
                                 ('debt', 'description', 'text', True),
                                 ('debt', 'expected_payoff', 'text', False),
                                 ('debt', 'from_char', 'text', False),
                                 ('debt', 'id', 'uuid', True),
                                 ('debt', 'item_id', 'text', True),
                                 ('debt', 'last_advanced', 'integer', False),
                                 ('debt', 'source', 'text', False),
                                 ('debt', 'status', 'text', True),
                                 ('debt', 'to_char', 'text', False),
                                 ('debt',
                                  'updated_at',
                                  'timestamp with time zone',
                                  False),
                                 ('hook', 'book_id', 'uuid', True),
                                 ('hook', 'chapter_created', 'integer', False),
                                 ('hook', 'chapter_resolved', 'integer', False),
                                 ('hook', 'content', 'jsonb', False),
                                 ('hook',
                                  'created_at',
                                  'timestamp with time zone',
                                  False),
                                 ('hook', 'description', 'text', True),
                                 ('hook', 'expected_payoff', 'text', False),
                                 ('hook', 'id', 'uuid', True),
                                 ('hook', 'item_id', 'text', True),
                                 ('hook', 'last_advanced', 'integer', False),
                                 ('hook', 'source', 'text', False),
                                 ('hook', 'status', 'text', True),
                                 ('hook',
                                  'updated_at',
                                  'timestamp with time zone',
                                  False),
                                 ('outline', 'book_id', 'uuid', True),
                                 ('outline', 'chapter_end', 'integer', False),
                                 ('outline', 'chapter_start', 'integer', False),
                                 ('outline', 'content', 'jsonb', True),
                                 ('outline',
                                  'created_at',
                                  'timestamp with time zone',
                                  False),
                                 ('outline', 'id', 'uuid', True),
                                 ('outline', 'type', 'text', True),
                                 ('outline',
                                  'updated_at',
                                  'timestamp with time zone',
                                  False),
                                 ('outline', 'volume_number', 'integer', True),
                                 ('world', 'book_id', 'uuid', True),
                                 ('world', 'core_laws', 'jsonb', True),
                                 ('world',
                                  'created_at',
                                  'timestamp with time zone',
                                  False),
                                 ('world', 'existence', 'jsonb', True),
                                 ('world', 'history_culture', 'jsonb', True),
                                 ('world', 'id', 'uuid', True),
                                 ('world', 'information', 'jsonb', True),
                                 ('world', 'society', 'jsonb', True),
                                 ('world', 'space_time', 'jsonb', True),
                                 ('world',
                                  'updated_at',
                                  'timestamp with time zone',
                                  False)),
 '20260609_product_schema': (('book', 'external_ref', 'text', False),
                             ('book', 'genre', 'text', False),
                             ('book', 'settings', 'jsonb', True),
                             ('book', 'status', 'text', True),
                             ('character', 'true_name', 'text', False),
                             ('novel_job', 'actor_ref', 'text', False),
                             ('novel_job', 'book_id', 'uuid', True),
                             ('novel_job',
                              'created_at',
                              'timestamp with time zone',
                              False),
                             ('novel_job', 'current_stage', 'text', False),
                             ('novel_job', 'error', 'jsonb', True),
                             ('novel_job', 'id', 'uuid', True),
                             ('novel_job', 'idempotency_key', 'text', False),
                             ('novel_job', 'operation', 'text', True),
                             ('novel_job', 'progress', 'numeric', False),
                             ('novel_job', 'request_id', 'text', False),
                             ('novel_job', 'request_payload', 'jsonb', True),
                             ('novel_job', 'result_payload', 'jsonb', True),
                             ('novel_job', 'status', 'text', True),
                             ('novel_job',
                              'updated_at',
                              'timestamp with time zone',
                              False),
                             ('novel_job', 'workflow_id', 'text', True),
                             ('novel_job', 'workflow_task_id', 'text', True),
                             ('novel_job_event',
                              'created_at',
                              'timestamp with time zone',
                              False),
                             ('novel_job_event', 'event_type', 'text', True),
                             ('novel_job_event', 'id', 'bigint', True),
                             ('novel_job_event', 'job_id', 'uuid', True),
                             ('novel_job_event', 'payload', 'jsonb', True),
                             ('novel_job_event', 'progress', 'numeric', False),
                             ('novel_job_event', 'stage_id', 'text', False),
                             ('novel_job_event', 'stage_name', 'text', False),
                             ('novel_resource_revision', 'actor_ref', 'text', False),
                             ('novel_resource_revision',
                              'after_content',
                              'jsonb',
                              False),
                             ('novel_resource_revision',
                              'base_version',
                              'integer',
                              False),
                             ('novel_resource_revision',
                              'before_content',
                              'jsonb',
                              False),
                             ('novel_resource_revision', 'book_id', 'uuid', True),
                             ('novel_resource_revision',
                              'created_at',
                              'timestamp with time zone',
                              False),
                             ('novel_resource_revision', 'diff', 'jsonb', False),
                             ('novel_resource_revision', 'diff_stats', 'jsonb', True),
                             ('novel_resource_revision',
                              'edit_intensity',
                              'text',
                              False),
                             ('novel_resource_revision', 'edit_mode', 'text', True),
                             ('novel_resource_revision', 'id', 'uuid', True),
                             ('novel_resource_revision', 'job_id', 'uuid', False),
                             ('novel_resource_revision', 'metadata', 'jsonb', True),
                             ('novel_resource_revision', 'reason', 'text', False),
                             ('novel_resource_revision', 'request_id', 'text', False),
                             ('novel_resource_revision', 'resource_key', 'text', True),
                             ('novel_resource_revision', 'resource_type', 'text', True),
                             ('novel_resource_revision', 'source', 'text', True),
                             ('novel_resource_revision',
                              'source_detail',
                              'text',
                              False),
                             ('novel_resource_revision', 'summary', 'text', False),
                             ('novel_resource_revision', 'version', 'integer', True),
                             ('novel_resource_revision', 'workflow_id', 'text', False),
                             ('novel_resource_revision',
                              'workflow_task_id',
                              'text',
                              False),
                             ('novel_resource_state', 'book_id', 'uuid', True),
                             ('novel_resource_state', 'content_hash', 'text', False),
                             ('novel_resource_state',
                              'created_at',
                              'timestamp with time zone',
                              False),
                             ('novel_resource_state',
                              'current_revision_id',
                              'uuid',
                              False),
                             ('novel_resource_state',
                              'current_version',
                              'integer',
                              True),
                             ('novel_resource_state', 'resource_key', 'text', True),
                             ('novel_resource_state', 'resource_type', 'text', True),
                             ('novel_resource_state',
                              'updated_at',
                              'timestamp with time zone',
                              False)),
 '20260613_book_scale_params': (('book', 'estimated_length', 'text', False),
                                ('book', 'words_per_chapter', 'text', False)),
 '20260613_book_soft_delete': (('book',
                                'deleted_at',
                                'timestamp with time zone',
                                False),),
 '20260720_novel_runtime_schema': (('chapter', 'post_hoc_status', 'text', False),
                                   ('character', 'essence', 'text', False))}
_INDEX_SIGNATURES = {'20260609_product_schema': (('idx_book_external_ref',
                              'book',
                              'btree',
                              True,
                              False,
                              True,
                              True,
                              ('external_ref',),
                              'external_ref IS NOT NULL'),
                             ('idx_chapter_book_number_unique',
                              'chapter',
                              'btree',
                              True,
                              False,
                              True,
                              True,
                              ('book_id', 'chapter_number'),
                              ''),
                             ('idx_novel_job_idempotency',
                              'novel_job',
                              'btree',
                              True,
                              False,
                              True,
                              True,
                              ('book_id', 'operation', 'idempotency_key'),
                              'idempotency_key IS NOT NULL')),
 '20260720_novel_runtime_schema': (('uq_novel_job_active_operation',
                                    'novel_job',
                                    'btree',
                                    True,
                                    False,
                                    True,
                                    True,
                                    ('book_id', 'operation'),
                                    "(status = ANY (ARRAY['queued'::text, "
                                    "'running'::text])) AND operation <> "
                                    "'chapter_polish'::text"),
                                   ('uq_novel_job_active_polish_chapter',
                                    'novel_job',
                                    'btree',
                                    True,
                                    True,
                                    True,
                                    True,
                                    ('book_id',
                                     'operation',
                                     "(request_payload ->> 'chapter_number'::text)"),
                                    "(status = ANY (ARRAY['queued'::text, "
                                    "'running'::text])) AND operation = "
                                    "'chapter_polish'::text"))}


def _expected_relation_kind(relation: str) -> str:
    if relation.startswith(("idx_", "uq_")):
        return "i"
    return "r"


def plugin_root(root: Path | None = None) -> Path:
    return root.resolve() if root else Path(__file__).resolve().parents[2]


def catalog_for(family: Family, root: Path | None = None) -> list[MigrationSpec]:
    if family != "novel":
        raise ValueError(f"unsupported migration family: {family}")
    directory = plugin_root(root) / "resources" / "migrations"
    return [
        MigrationSpec(
            family="novel",
            migration_id=migration_id,
            path=directory / f"{migration_id}.sql",
            relations=frozenset(relations),
            columns=frozenset(columns),
            absent_columns=frozenset(absent_columns),
            column_signatures=frozenset(_COLUMN_SIGNATURES.get(migration_id, ())),
            constraints=frozenset(CONSTRAINT_SIGNATURES.get(migration_id, ())),
            indexes=frozenset(_INDEX_SIGNATURES.get(migration_id, ())),
            relation_signatures=frozenset(
                (relation, _expected_relation_kind(relation))
                for relation in relations
            ),
            defaults=frozenset(DEFAULT_SIGNATURES.get(migration_id, ())),
        )
        for migration_id, relations, columns, absent_columns in _CATALOG["novel"]
    ]
