"""PostgreSQL defaults required by Novel API runtime INSERT contracts."""

DEFAULT_SIGNATURES = {'20260601_novel_api_baseline': (('book', 'created_at', 'now()'),
                                 ('book', 'id', 'gen_random_uuid()'),
                                 ('book', 'settings', "'{}'::jsonb"),
                                 ('book', 'status', "'draft'::text"),
                                 ('book', 'story_plan', "'{}'::jsonb"),
                                 ('book', 'style_profile', "'{}'::jsonb"),
                                 ('book', 'updated_at', 'now()'),
                                 ('chapter', 'character_diff', "'{}'::jsonb"),
                                 ('chapter', 'character_minor', "'{}'::jsonb"),
                                 ('chapter', 'character_state', "'{}'::jsonb"),
                                 ('chapter', 'created_at', 'now()'),
                                 ('chapter', 'guide', "'{}'::jsonb"),
                                 ('chapter', 'id', 'gen_random_uuid()'),
                                 ('chapter', 'status', "'draft'::text"),
                                 ('chapter', 'story_confirmed', "'{}'::jsonb"),
                                 ('chapter', 'storyboard', "'{}'::jsonb"),
                                 ('chapter', 'updated_at', 'now()'),
                                 ('chapter', 'word_count', '0'),
                                 ('chapter', 'world_events', "'{}'::jsonb"),
                                 ('chapter', 'world_rulings', "'{}'::jsonb"),
                                 ('chapter', 'world_state', "'{}'::jsonb"),
                                 ('character', 'aliases', "'[]'::jsonb"),
                                 ('character', 'arc_description', "'{}'::jsonb"),
                                 ('character', 'beliefs', "'{}'::jsonb"),
                                 ('character', 'bottom_line', "'{}'::jsonb"),
                                 ('character', 'contradictions', "'{}'::jsonb"),
                                 ('character', 'created_at', 'now()'),
                                 ('character', 'deep_fear', "'{}'::jsonb"),
                                 ('character', 'extras', "'{}'::jsonb"),
                                 ('character', 'id', 'gen_random_uuid()'),
                                 ('character', 'secrets', "'[]'::jsonb"),
                                 ('character', 'traumas', "'[]'::jsonb"),
                                 ('character', 'updated_at', 'now()'),
                                 ('character', 'voice', "'{}'::jsonb"),
                                 ('character', 'world_position', "'{}'::jsonb"),
                                 ('debt', 'content', "'{}'::jsonb"),
                                 ('debt', 'created_at', 'now()'),
                                 ('debt', 'id', 'gen_random_uuid()'),
                                 ('debt', 'status', "'open'::text"),
                                 ('debt', 'updated_at', 'now()'),
                                 ('hook', 'content', "'{}'::jsonb"),
                                 ('hook', 'created_at', 'now()'),
                                 ('hook', 'id', 'gen_random_uuid()'),
                                 ('hook', 'status', "'open'::text"),
                                 ('hook', 'updated_at', 'now()'),
                                 ('outline', 'content', "'{}'::jsonb"),
                                 ('outline', 'created_at', 'now()'),
                                 ('outline', 'id', 'gen_random_uuid()'),
                                 ('outline', 'updated_at', 'now()'),
                                 ('outline', 'volume_number', '1'),
                                 ('world', 'core_laws', "'{}'::jsonb"),
                                 ('world', 'created_at', 'now()'),
                                 ('world', 'existence', "'{}'::jsonb"),
                                 ('world', 'history_culture', "'{}'::jsonb"),
                                 ('world', 'id', 'gen_random_uuid()'),
                                 ('world', 'information', "'{}'::jsonb"),
                                 ('world', 'society', "'{}'::jsonb"),
                                 ('world', 'space_time', "'{}'::jsonb"),
                                 ('world', 'updated_at', 'now()')),
 '20260609_product_schema': (('novel_job', 'created_at', 'now()'),
                             ('novel_job', 'error', "'{}'::jsonb"),
                             ('novel_job', 'id', 'gen_random_uuid()'),
                             ('novel_job', 'progress', '0'),
                             ('novel_job', 'request_payload', "'{}'::jsonb"),
                             ('novel_job', 'result_payload', "'{}'::jsonb"),
                             ('novel_job', 'status', "'queued'::text"),
                             ('novel_job', 'updated_at', 'now()'),
                             ('novel_job_event', 'created_at', 'now()'),
                             ('novel_job_event',
                              'id',
                              "nextval('novel_job_event_id_seq'::regclass)"),
                             ('novel_job_event', 'payload', "'{}'::jsonb"),
                             ('novel_resource_revision', 'created_at', 'now()'),
                             ('novel_resource_revision', 'diff_stats', "'{}'::jsonb"),
                             ('novel_resource_revision',
                              'edit_mode',
                              "'replace'::text"),
                             ('novel_resource_revision', 'id', 'gen_random_uuid()'),
                             ('novel_resource_revision', 'metadata', "'{}'::jsonb"),
                             ('novel_resource_state', 'created_at', 'now()'),
                             ('novel_resource_state', 'current_version', '1'),
                             ('novel_resource_state', 'updated_at', 'now()')),
 '20260613_book_scale_params': (('book', 'estimated_length', "'中'::text"),
                                ('book', 'words_per_chapter', "'2000-2500'::text"))}
